baseURL: "https://fxiangecon.github.io" 
title: Fengfan Xiang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: /research/
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: CV
          url: "/cv_xiang_aug2025.pdf"
          # weight: 

params:
    description: "Welcome to my personal website!"
    author: Fengfan Xiang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: True
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Fengfan Xiang
          subtitle: "I am a Ph.D. Candidate in the [Department of Economics, University of Western Ontario.](https://economics.uwo.ca)
          \n <br> &nbsp; \n\n
          My research interests include monetary economics, financial economics, and macroeconomics."
          imageUrl: "photo.jpg"
          imageWidth:  160
          imageHeight: 180
          imageTitle: Fengfan Xiang
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: "/cv_xiang_aug2025.pdf"
           
    socialIcons:
        - name: Email
          url: "mailto:fxiang8@uwo.ca"
        - name: CV
          url: "/cv_xiang_aug2025.pdf"
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: GitHub
          url: https://github.com/fxiangecon
        - name: Twitter
          url: https://twitter.com/FengfanXiang

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Fengfan Xiang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2