relativeURLs = true
title = "Fengfan Xiang"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. candidate in Economics, University of Western Ontario"
    logo = "fengfan_headshot.jpg" 

[services]
  [services.googleAnalytics]
    ID = 'G-LG3FT0FV6E'
