relativeURLs = true
title = "Maghfira (Afi) Ramadhani"
theme = "academimal-theme"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Student in Economics, Georgia Institute of Technology"
    logo = "Afi_headshot.jpg" 

[services]
  [services.googleAnalytics]
    ID = 'G-LG3FT0FV6E'
