<<<<<<< HEAD
baseURL: "https://fxiangecon.github.io/"
title: "Fengfan Xiang"
# paginate: 20
=======
baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Moritz-Maria von Igelfeld
>>>>>>> 56e5c5485b0f57c2f66a2a4ef28ef192f0203bfe
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
<<<<<<< HEAD
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: /research/
=======
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
>>>>>>> 56e5c5485b0f57c2f66a2a4ef28ef192f0203bfe
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
<<<<<<< HEAD
        - name: CV
          url: "/cv_xiang_apr2024.pdf"
          # weight: 

params:
    description: "Welcome to my personal website!"
    author: Fengfan Xiang
=======
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Moritz-Maria von Igelfeld
>>>>>>> 56e5c5485b0f57c2f66a2a4ef28ef192f0203bfe
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: True
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
<<<<<<< HEAD
          title: Fengfan Xiang
          subtitle: "I am a Ph.D. Candidate in the [Department of Economics, University of Western Ontario.](https://economics.uwo.ca)
          \n <br> &nbsp; \n\n
          My research interests include monetary economics, financial economics, and macroeconomics."
          imageUrl: "photo.jpg"
          imageWidth:  160
          imageHeight: 180
          imageTitle: Fengfan Xiang
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: CV
              url: "/cv_xiang_apr2024.pdf"
           
    socialIcons:
        - name: Email
          url: "mailto:fxiang8@uwo.ca"
        - name: CV
          url: "/cv_xiang_apr2024.pdf"
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: GitHub
          url: https://github.com/fxiangecon
=======
          title: Professor Dr von Igelfeld
          subtitle: "I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:moritz.maria.von.igelfeld@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
>>>>>>> 56e5c5485b0f57c2f66a2a4ef28ef192f0203bfe
        - name: Twitter
          url: https://twitter.com/FengfanXiang

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Fengfan Xiang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2